# arrivalstory-prod: i-0624b56c404d73a81, t4g.small, us-east-1
[lily]
arrivalstory.com ansible_host=107.21.47.253 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/arrivalstory.pem

[lily:vars]
ansible_python_interpreter=/usr/bin/python3
