#!/usr/bin/env bash
# Pull the web fonts down from Google and serve them ourselves.
#
#   ./scripts/vendor-fonts.sh
#
# Writes frontend/public/fonts/*.woff2 and frontend/src/styles/fonts.css.
# Re-run it to change which families or weights we use: edit FAMILIES below,
# run this, commit the result.
#
# Why we host them: a <link> to fonts.googleapis.com sends every visitor's IP
# address to Google before they have agreed to anything, which is a live
# GDPR problem (a Munich court awarded damages over exactly that in 2022).
# Self-hosted, nobody but us sees the request — and it is faster, since it
# drops a DNS lookup, a TLS handshake and a round trip to a third party.
#
# All five families are SIL Open Font License 1.1, which permits this
# explicitly; the licences ride along in frontend/public/fonts/licences/.
set -euo pipefail
cd "$(dirname "$0")/.."

FAMILIES="family=Great+Vibes&family=Cormorant+Garamond:ital,wght@0,600;1,600&family=Fredoka:wght@500;600&family=Quicksand:wght@600;700&family=Fraunces:opsz,wght@9..144,600&display=swap"
# a modern UA, or Google serves us ttf instead of woff2
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

OUT=frontend/public/fonts
CSS=frontend/src/styles/fonts.css
mkdir -p "$OUT/licences" "$(dirname "$CSS")"

raw=$(mktemp)
curl -sfS -A "$UA" "https://fonts.googleapis.com/css2?$FAMILIES" -o "$raw"
grep -q "format('woff2')" "$raw" || { echo "expected woff2, got something else"; exit 1; }

# Walk the stylesheet, download each file under a name that says what it is,
# and rewrite the url() to point at ourselves.
python3 - "$raw" "$OUT" "$CSS" <<'PY'
import re, subprocess, sys
from pathlib import Path

raw, out, css_path = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
css = raw.read_text()

blocks = css.split("@font-face")
header = ["/* Generated by scripts/vendor-fonts.sh — do not edit by hand. */"]
rendered, seen = [], {}
subset = None
for line in css.splitlines():
    m = re.match(r"/\* ([a-z0-9-]+) \*/", line.strip())
    if m:
        subset = m.group(1)

for block in blocks[1:]:
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    style = re.search(r"font-style:\s*(\w+)", block).group(1)
    weight = re.search(r"font-weight:\s*([\d ]+)", block).group(1).strip().replace(" ", "-")
    url = re.search(r"url\((https://[^)]+)\)", block).group(1)
    # the subset comment precedes the block it belongs to
    idx = css.index(block)
    before = css[:idx]
    sub = (re.findall(r"/\* ([a-z0-9-]+) \*/", before) or ["latin"])[-1]
    slug = re.sub(r"[^a-z0-9]+", "-", fam.lower()).strip("-")
    name = f"{slug}-{weight}-{style}-{sub}.woff2"
    if name in seen:
        name = f"{slug}-{weight}-{style}-{sub}-{seen[name]}.woff2"
    seen[name] = seen.get(name, 0) + 1
    subprocess.run(["curl", "-sfS", url, "-o", str(out / name)], check=True)
    rendered.append("@font-face" + block.replace(url, f"/fonts/{name}"))

css_path.write_text("\n".join(header) + "\n" + "".join(rendered).rstrip() + "\n")
print(f"{len(rendered)} font files -> {out}")
PY
rm -f "$raw"

# The OFL asks that the licence travel with the fonts.
for f in greatvibes cormorantgaramond fredoka quicksand fraunces; do
  curl -sfS "https://raw.githubusercontent.com/google/fonts/main/ofl/$f/OFL.txt" \
    -o "$OUT/licences/$f-OFL.txt"
done

echo "licences -> $OUT/licences"
du -sh "$OUT" | awk '{print "total: "$1}'
