export const THEMES = {
  lily: {
    id: 'lily',
    label: 'Lily',
    description: 'Soft violet',
    gender: 'neutral',
    accent: '#c026d3',
    accentHover: '#a21caf',
    accentLight: '#fdf4ff',
    accentMid: '#e879f9',
    accentBorder: '#f0abfc',
    headerBorder: '#f0abfc',
    previewGradient: 'linear-gradient(135deg, #fdf4ff 0%, #fae8ff 100%)',
    scriptColor: '#c026d3',
    swatchGradient: 'linear-gradient(135deg, #e879f9, #c026d3)',
  },
  blossom: {
    id: 'blossom',
    label: 'Blossom',
    description: 'Blush rose',
    gender: 'girl',
    accent: '#e11d48',
    accentHover: '#be123c',
    accentLight: '#fff1f2',
    accentMid: '#fb7185',
    accentBorder: '#fda4af',
    headerBorder: '#fda4af',
    previewGradient: 'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 100%)',
    scriptColor: '#e11d48',
    swatchGradient: 'linear-gradient(135deg, #fb7185, #e11d48)',
  },
  wildflower: {
    id: 'wildflower',
    label: 'Wildflower',
    description: 'Soft lavender',
    gender: 'girl',
    accent: '#7c3aed',
    accentHover: '#6d28d9',
    accentLight: '#f5f3ff',
    accentMid: '#a78bfa',
    accentBorder: '#c4b5fd',
    headerBorder: '#c4b5fd',
    previewGradient: 'linear-gradient(135deg, #f5f3ff 0%, #ede9fe 100%)',
    scriptColor: '#7c3aed',
    swatchGradient: 'linear-gradient(135deg, #a78bfa, #7c3aed)',
  },
  ocean: {
    id: 'ocean',
    label: 'Ocean',
    description: 'Sky to deep blue',
    gender: 'boy',
    accent: '#0284c7',
    accentHover: '#0369a1',
    accentLight: '#f0f9ff',
    accentMid: '#38bdf8',
    accentBorder: '#7dd3fc',
    headerBorder: '#7dd3fc',
    previewGradient: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)',
    scriptColor: '#0284c7',
    swatchGradient: 'linear-gradient(135deg, #38bdf8, #0284c7)',
  },
  forest: {
    id: 'forest',
    label: 'Sage Garden',
    description: 'Soft sage green',
    gender: 'boy',
    accent: '#059669',
    accentHover: '#047857',
    accentLight: '#f0fdf4',
    accentMid: '#34d399',
    accentBorder: '#6ee7b7',
    headerBorder: '#6ee7b7',
    previewGradient: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
    scriptColor: '#059669',
    swatchGradient: 'linear-gradient(135deg, #34d399, #059669)',
  },
  golden: {
    id: 'golden',
    label: 'Golden Hour',
    description: 'Warm amber & cream',
    gender: 'neutral',
    accent: '#b45309',
    accentHover: '#92400e',
    accentLight: '#fffbeb',
    accentMid: '#fbbf24',
    accentBorder: '#fcd34d',
    headerBorder: '#fcd34d',
    previewGradient: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)',
    scriptColor: '#b45309',
    swatchGradient: 'linear-gradient(135deg, #fbbf24, #b45309)',
  },
};

export const THEMES_BY_GENDER = {
  girl: [THEMES.blossom, THEMES.wildflower],
  boy: [THEMES.ocean, THEMES.forest],
  neutral: [THEMES.golden, THEMES.lily],
};

export function getTheme(id) {
  return THEMES[id] || THEMES.lily;
}
