---
- name: Install lily systemd unit
  template:
    src: lily.service.j2
    dest: /etc/systemd/system/lily.service
    owner: root
    group: root
    mode: '0644'
  notify: restart lily app

- name: Enable and start lily
  systemd:
    name: lily
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install lily media worker systemd unit
  template:
    src: lily-worker.service.j2
    dest: /etc/systemd/system/lily-worker.service
    owner: root
    group: root
    mode: '0644'
  notify: restart lily worker

- name: Enable and start lily media worker
  systemd:
    name: lily-worker
    state: started
    enabled: yes
    daemon_reload: yes
